name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        part: ["00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19"]
    steps:
      - uses: actions/setup-python@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.22"
      - uses: actions/checkout@v3
      - name: Get data from Go build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/golangci-lint
            ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/go.sum') }}
      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/**.go
            "!test/"
            go.mod
            go.sum
            Makefile
      - name: Run Go Tests
        run: |
          NUM_SPLIT=20
          make split-test-packages
          make test-group-${{matrix.part}}

  unit-test-check:
    name: Unit Test Check
    runs-on: ubuntu-latest
    needs: tests
    if: always()
    steps:
      - name: Get workflow conclusion
        id: workflow_conclusion
        uses: nick-fields/retry@v2
        with:
          max_attempts: 2
          retry_on: error
          timeout_seconds: 60
          command: |
              jobs=$(curl https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs)
              job_statuses=$(echo "$jobs" | jq -r '.jobs[] | .conclusion')

              for status in $job_statuses
              do
                echo "Status: $status"
                if [[ "$status" == "failure" ]]; then
                  echo "Some or all tests have failed!"
                  exit 1
                fi
              done

              echo "All tests have passed!"
